#!/usr/bin/env python3
"""Convert the supplied Tesla JPEG to LVGL RGB565; generate Polish Montserrat fonts.
Requires Pillow. Usage: python tools/tesla_assets.py /path/to/Montserrat[wght].ttf
Font source: https://github.com/google/fonts/tree/main/ofl/montserrat (OFL).
"""
from pathlib import Path
import sys
from PIL import Image, ImageFont, ImageDraw
ROOT = Path(__file__).resolve().parents[1]

def array(data):
    return '\n'.join('    ' + ', '.join(f'0x{x:02x}' for x in data[i:i+20]) + ',' for i in range(0, len(data), 20))

im = Image.open(ROOT / 'main/assets/images/tesla_m5stopwatch_466x466.jpg').convert('RGB')
assert im.size == (466, 466)
raw = bytearray()
for r, g, b in im.get_flattened_data():
    pixel = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    raw.extend((pixel & 255, pixel >> 8))
(ROOT / 'main/assets/images/icon_tesla.c').write_text('''// Generated by tools/tesla_assets.py from the supplied JPEG. RGB565 little endian.
#include <lvgl.h>
static const uint8_t LV_ATTRIBUTE_MEM_ALIGN icon_tesla_map[] = {
''' + array(raw) + '''
};
const lv_image_dsc_t icon_tesla = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_RGB565,
    .header.w = 466,
    .header.h = 466,
    .header.stride = 932,
    .data_size = sizeof(icon_tesla_map),
    .data = icon_tesla_map,
};
''')

chars = sorted(set(chr(i) for i in range(32, 127)) | set('ĄĆĘŁŃÓŚŹŻąćęłńóśźż'))
for size in (26, 32):
    font = ImageFont.truetype(sys.argv[1], size)
    font.set_variation_by_axes([600])
    ascent, descent = font.getmetrics()
    data = bytearray()
    glyphs = ['    {0},']
    for c in chars:
        x0,y0,x1,y1 = font.getbbox(c, anchor='ls')
        w,h = x1-x0,y1-y0
        image = Image.new('L', (max(1,w), max(1,h)))
        ImageDraw.Draw(image).text((-x0,-y0), c, font=font, fill=255, anchor='ls')
        pixels = list(image.get_flattened_data()) if w and h else []
        start = len(data)
        for i in range(0,len(pixels),2):
            hi = (pixels[i]*15+127)//255
            lo = (pixels[i+1]*15+127)//255 if i+1<len(pixels) else 0
            data.append(hi*16+lo)
        glyphs.append(f'    {{.bitmap_index={start}, .adv_w={round(font.getlength(c)*16)}, .box_w={w}, .box_h={h}, .ofs_x={x0}, .ofs_y={-y1}}},')
    name = f'tesla_text_{size}'
    text = f'''// Generated by tools/tesla_assets.py. Montserrat SemiBold, OFL (tesla_font_OFL.txt).
#include <lvgl.h>
static const uint8_t glyph_bitmap[] = {{
{array(data)}
}};
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{chr(10).join(glyphs)}
}};
static const uint16_t unicode_list[] = {{{', '.join(str(ord(c)-32) for c in chars)}}};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{{{
    .range_start=32, .range_length={ord(chars[-1])-31}, .glyph_id_start=1,
    .unicode_list=unicode_list, .glyph_id_ofs_list=NULL, .list_length={len(chars)},
    .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY,
}}}};
static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap=glyph_bitmap, .glyph_dsc=glyph_dsc, .cmaps=cmaps,
    .kern_dsc=NULL, .kern_scale=0, .cmap_num=1, .bpp=4, .kern_classes=0, .bitmap_format=0,
}};
const lv_font_t {name} = {{
    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
    .line_height={ascent+descent}, .base_line={descent}, .subpx=LV_FONT_SUBPX_NONE,
    .underline_position=-2, .underline_thickness=1, .dsc=&font_dsc,
}};
'''
    (ROOT / f'main/assets/fonts/{name}.c').write_text(text)
print('Generated 466x466 RGB565 Tesla asset and two Polish fonts.')
